[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
fs_permissions = [{ access = "read-write", path = "./"}]

[rpc_endpoints]
theNet="http://127.0.0.1:8545"

[fuzz]                                                                                                            
runs = 500

# See more config options https://book.getfoundry.sh/reference/config/